<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%bangphanconggiangday}}".
 *
 * @property int $id
 * @property string $name
 * @property string $created_at
 * @property string $updated_at
 * @property string $ngayky
 * @property string $filedinhkem
 * @property int $bomon_id
 * @property int $hocky_id
 * @property int $namhoc_id
 * @property int $HDGD_TKB_BPCGD__id
 *
 * @property HdgdTkbBpcgd $hDGDTKBBPCGD
 * @property Bomon $bomon
 * @property Hocky $hocky
 * @property Namhoc $namhoc
 */
class Bangphanconggiangday extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%bangphanconggiangday}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'bomon_id', 'hocky_id', 'namhoc_id'], 'required', 'message' => 'Chưa điền {attribute}'],
            [['created_at', 'updated_at', 'ngayky'], 'safe'],
            [['bomon_id', 'hocky_id', 'namhoc_id', 'HDGD_TKB_BPCGD__id'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['filedinhkem'], 'string', 'max' => 200],
            [['HDGD_TKB_BPCGD__id'], 'exist', 'skipOnError' => true, 'targetClass' => HdgdTkbBpcgd::className(), 'targetAttribute' => ['HDGD_TKB_BPCGD__id' => 'id']],
            [['bomon_id'], 'exist', 'skipOnError' => true, 'targetClass' => Bomon::className(), 'targetAttribute' => ['bomon_id' => 'id']],
            [['hocky_id'], 'exist', 'skipOnError' => true, 'targetClass' => Hocky::className(), 'targetAttribute' => ['hocky_id' => 'id']],
            [['namhoc_id'], 'exist', 'skipOnError' => true, 'targetClass' => Namhoc::className(), 'targetAttribute' => ['namhoc_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Ngày cập nhật',
            'ngayky' => 'Ngày ký',
            'filedinhkem' => 'File đính kèm',
            'bomon_id' => 'Bộ môn',
            'hocky_id' => 'Học kỳ',
            'namhoc_id' => 'Năm học',
            'HDGD_TKB_BPCGD__id' => 'Loại tài liệu',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHDGDTKBBPCGD()
    {
        return $this->hasOne(HdgdTkbBpcgd::className(), ['id' => 'HDGD_TKB_BPCGD__id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBomon()
    {
        return $this->hasOne(Bomon::className(), ['id' => 'bomon_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHocky()
    {
        return $this->hasOne(Hocky::className(), ['id' => 'hocky_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNamhoc()
    {
        return $this->hasOne(Namhoc::className(), ['id' => 'namhoc_id']);
    }

    public function beforeSave($insert)
    {
        $file = UploadedFile::getInstance($this,'filedinhkem');
        if(is_null($file)){
            if($insert){
                $this->filedinhkem ='nofile.jpg';
            }
            else{
                $old = Bangphanconggiangday::findOne($this->id);
                $this->filedinhkem = $old->filedinhkem;
            }
        }
        else{
            if(!$insert){
                $old = Bangphanconggiangday::findOne($this->id);
                if($old->filedinhkem != 'nofile.jpg'){
                    $path = dirname(dirname(__DIR__)).'/files/'.$old->filedinhkem;
                    unlink($path);
                }
            }
            $fileName = time().myFuncs::sinhDuongDan($file->name);
            $path = dirname(dirname(__DIR__)).'/files/'.$fileName;
            $file->saveAs($path);
            $this->filedinhkem = $fileName;

        }
        if($insert)
            $this->created_at = new Expression("NOW()");
        else
            $this->updated_at = new Expression("NOW()");
        $this->HDGD_TKB_BPCGD__id = 1;
        $this->ngayky = myFuncs::dayMonthYeartoYearMonthDay($this->ngayky);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $file = $this->filedinhkem;
        if($file != 'nofile.jpg');
        $path = dirname(dirname(__DIR__)).'/files'.$file;
        if(is_file($path))
            unlink($path);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
