<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%ctdt_dchp}}".
 *
 * @property int $id
 * @property string $name
 * @property int $loaitailieu_id
 *
 * @property Chuongtrinhdaotao[] $chuongtrinhdaotaos
 * @property Loaitailieu $loaitailieu
 * @property Decuonghocphan[] $decuonghocphans
 */
class CtdtDchp extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%ctdt_dchp}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required', 'message' => 'Chưa điền {attribute}'],
            [['loaitailieu_id'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['loaitailieu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Loaitailieu::className(), 'targetAttribute' => ['loaitailieu_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên loại tài liệu',
            'loaitailieu_id' => 'Loại tài liệu',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChuongtrinhdaotaos()
    {
        return $this->hasMany(Chuongtrinhdaotao::className(), ['CTDT_DCHP_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoaitailieu()
    {
        return $this->hasOne(Loaitailieu::className(), ['id' => 'loaitailieu_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDecuonghocphans()
    {
        return $this->hasMany(Decuonghocphan::className(), ['CTDT_DCHP_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->loaitailieu_id = 2;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
