<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%dapan}}".
 *
 * @property int $id
 * @property string $name
 * @property string $filedinhkem
 * @property string $created_at
 * @property string $updated_at
 * @property int $nganhangdethi_id
 * @property int $NHDT_DA_id
 *
 * @property NhdtDa $nHDTDA
 * @property Nganhangdethi $nganhangdethi
 */
class Dapan extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dapan}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'nganhangdethi_id'], 'required', 'message' => 'Chưa điền {attribute}'],
            [['created_at', 'updated_at'], 'safe'],
            [['nganhangdethi_id', 'NHDT_DA_id'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['filedinhkem'], 'string', 'max' => 200],
            [['NHDT_DA_id'], 'exist', 'skipOnError' => true, 'targetClass' => NhdtDa::className(), 'targetAttribute' => ['NHDT_DA_id' => 'id']],
            [['nganhangdethi_id'], 'exist', 'skipOnError' => true, 'targetClass' => Nganhangdethi::className(), 'targetAttribute' => ['nganhangdethi_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên',
            'filedinhkem' => 'File đính kèm',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Ngày cập nhật',
            'nganhangdethi_id' => 'Ngân hàng đề thi',
            'NHDT_DA_id' => 'Loại tài liệu',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNHDTDA()
    {
        return $this->hasOne(NhdtDa::className(), ['id' => 'NHDT_DA_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNganhangdethi()
    {
        return $this->hasOne(Nganhangdethi::className(), ['id' => 'nganhangdethi_id']);
    }

    public function beforeSave($insert)
    {
        $file = UploadedFile::getInstance($this,'filedinhkem');
        if(is_null($file)){
            if($insert){
                $this->filedinhkem ='nofile.jpg';
            }
            else{
                $old = Dapan::findOne($this->id);
                $this->filedinhkem = $old->filedinhkem;
            }
        }
        else{
            if(!$insert){
                $old = Dapan::findOne($this->id);
                if($old->filedinhkem != 'nofile.jpg'){
                    $path = dirname(dirname(__DIR__)).'/files/'.$old->filedinhkem;
                    unlink($path);
                }
            }
            $fileName = time().myFuncs::sinhDuongDan($file->name);
            $path = dirname(dirname(__DIR__)).'/files/'.$fileName;
            $file->saveAs($path);
            $this->filedinhkem = $fileName;

        }
        if($insert)
            $this->created_at = new Expression("NOW()");
        else
            $this->updated_at = new Expression("NOW()");
        $this->	NHDT_DA_id = 2;
//        $this->ngaybanhanh = myFuncs::dayMonthYeartoYearMonthDay($this->ngaybanhanh);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $file = $this->filedinhkem;
        if($file != 'nofile.jpg');
        $path = dirname(dirname(__DIR__)).'/files'.$file;
        if(is_file($path))
            unlink($path);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
