<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%dbtl_dcot_lt_pcct}}".
 *
 * @property int $id
 * @property string $name
 * @property int $loaitailieu_id
 *
 * @property Loaitailieu $loaitailieu
 * @property Debaitaplon[] $debaitaplons
 * @property Decuongontap[] $decuongontaps
 * @property Lichthi[] $lichthis
 * @property Phancongcoithi[] $phancongcoithis
 */
class DbtlDcotLtPcct extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dbtl_dcot_lt_pcct}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['loaitailieu_id'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['loaitailieu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Loaitailieu::className(), 'targetAttribute' => ['loaitailieu_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên',
            'loaitailieu_id' => 'Loại tài liệu',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoaitailieu()
    {
        return $this->hasOne(Loaitailieu::className(), ['id' => 'loaitailieu_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDebaitaplons()
    {
        return $this->hasMany(Debaitaplon::className(), ['DBTL_DCOT_LT_PCCT_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDecuongontaps()
    {
        return $this->hasMany(Decuongontap::className(), ['DBTL_DCOT_LT_PCCT_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLichthis()
    {
        return $this->hasMany(Lichthi::className(), ['DBTL_DCOT_LT_PCCT_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPhancongcoithis()
    {
        return $this->hasMany(Phancongcoithi::className(), ['DBTL_DCOT_LT_PCCT_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->loaitailieu_id  = 7;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
