<?php

namespace common\models;

use Yii;
use yii\db\Expression;

/**
 * This is the model class for table "{{%dkthiduatapthe}}".
 *
 * @property int $id
 * @property string $name
 * @property int $namhoc_id
 * @property int $khoa_id
 * @property string $ngaydk
 * @property string $created_at
 * @property string $updated_at
 * @property int $sogiangvien
 * @property int $sogiangviencomat
 * @property string $CTNA_GDLT
 * @property string $CTNA_HDTH
 * @property string $CTNA_HDTN
 * @property string $CTNA_CT
 * @property string $CTNA_KN
 * @property string $CTNB_VGT
 * @property string $CTNB_NCKH
 * @property string $CTNB_CMNV
 * @property string $CTNB_TGPT
 * @property string $CTNB_CHPL
 *
 * @property Namhoc $namhoc
 * @property Khoa $khoa
 */
class Dkthiduatapthe extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%dkthiduatapthe}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'namhoc_id', 'khoa_id', 'sogiangvien', 'sogiangviencomat', 'CTNA_GDLT', 'CTNA_HDTH', 'CTNA_HDTN', 'CTNA_CT', 'CTNA_KN', 'CTNB_VGT', 'CTNB_NCKH', 'CTNB_CMNV', 'CTNB_TGPT', 'CTNB_CHPL'], 'required', 'message' => 'Chưa điền {attribute}'],
            [['namhoc_id', 'khoa_id', 'sogiangvien', 'sogiangviencomat'], 'integer'],
            [['ngaydk', 'created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 100],
            [['CTNA_GDLT', 'CTNA_HDTH', 'CTNA_HDTN', 'CTNA_CT', 'CTNA_KN', 'CTNB_VGT', 'CTNB_NCKH', 'CTNB_CMNV', 'CTNB_TGPT', 'CTNB_CHPL'], 'string', 'max' => 50],
            [['namhoc_id'], 'exist', 'skipOnError' => true, 'targetClass' => Namhoc::className(), 'targetAttribute' => ['namhoc_id' => 'id']],
            [['khoa_id'], 'exist', 'skipOnError' => true, 'targetClass' => Khoa::className(), 'targetAttribute' => ['khoa_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Tên'),
            'namhoc_id' => Yii::t('app', 'Năm học'),
            'khoa_id' => Yii::t('app', 'Tên đơn vị'),
            'ngaydk' => Yii::t('app', 'Ngày đăng ký'),
            'created_at' => Yii::t('app', 'Ngày tạo'),
            'updated_at' => Yii::t('app', 'Ngày cập nhật'),
            'sogiangvien' => Yii::t('app', 'Số giảng viên'),
            'sogiangviencomat' => Yii::t('app', 'Số giảng viên có mặt'),
            'CTNA_GDLT' => Yii::t('app', 'Giảng dạy lý thuyết: Hệ chính quy ĐH, CĐ'),
            'CTNA_HDTH' => Yii::t('app', 'Hướng dẫn thực hành, thí nghiệm'),
            'CTNA_HDTN' => Yii::t('app', 'Hướng dẫn tốt nghiệp'),
            'CTNA_CT' => Yii::t('app', 'Chấm thi, hỏi thi'),
            'CTNA_KN' => Yii::t('app', 'Công tác kiêm nhiệm'),
            'CTNB_VGT' => Yii::t('app', 'Viết giáo trình, bài giảng'),
            'CTNB_NCKH' => Yii::t('app', 'Nghiên cứu khoa học'),
            'CTNB_CMNV' => Yii::t('app', 'Học tập chuyên môn, nghiệp vụ'),
            'CTNB_TGPT' => Yii::t('app', 'Tham gia các phong trào, các hoạt động của Nhà trường'),
            'CTNB_CHPL' => Yii::t('app', 'Chấp hành tốt pháp luật của Nhà nước, các quy định của ngành, Trường'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNamhoc()
    {
        return $this->hasOne(Namhoc::className(), ['id' => 'namhoc_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKhoa()
    {
        return $this->hasOne(Khoa::className(), ['id' => 'khoa_id']);
    }
    public function beforeSave($insert)
    {
        if($insert)
            $this->created_at = new Expression("NOW()");
        else
            $this->updated_at = new Expression("NOW()");
//        $this->HDGD_TKB_BPCGD__id = 1;
        $this->ngaydk = myFuncs::dayMonthYeartoYearMonthDay($this->ngaydk);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}

