<?php

namespace common\models;

use Yii;
use yii\db\Expression;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%ketquadanhgiahocphan}}".
 *
 * @property int $id
 * @property string $name
 * @property string $created_at
 * @property string $updated_at
 * @property string $ngaythi
 * @property string $canbocoithi
 * @property string $canbochamthi
 * @property string $nhomhocphan
 * @property string $filedinhkem
 * @property int $hocky_id
 * @property int $namhoc_id
 * @property int $monhoc_id
 * @property int $loaitailieu_id
 *
 * @property Hocky $hocky
 * @property Loaitailieu $loaitailieu
 * @property Monhoc $monhoc
 * @property Namhoc $namhoc
 */
class Ketquadanhgiahocphan extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%ketquadanhgiahocphan}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'hocky_id', 'namhoc_id', 'monhoc_id'], 'required', 'message' => 'Chưa điền {attribute}'],
            [['created_at', 'updated_at', 'ngaythi'], 'safe'],
            [['hocky_id', 'namhoc_id', 'monhoc_id', 'loaitailieu_id'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['canbocoithi', 'canbochamthi', 'filedinhkem'], 'string', 'max' => 200],
            [['nhomhocphan'], 'string', 'max' => 10],
            [['hocky_id'], 'exist', 'skipOnError' => true, 'targetClass' => Hocky::className(), 'targetAttribute' => ['hocky_id' => 'id']],
            [['loaitailieu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Loaitailieu::className(), 'targetAttribute' => ['loaitailieu_id' => 'id']],
            [['monhoc_id'], 'exist', 'skipOnError' => true, 'targetClass' => Monhoc::className(), 'targetAttribute' => ['monhoc_id' => 'id']],
            [['namhoc_id'], 'exist', 'skipOnError' => true, 'targetClass' => Namhoc::className(), 'targetAttribute' => ['namhoc_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Ngày cập nhật',
            'ngaythi' => 'Ngày thi',
            'canbocoithi' => 'Cán bộ coi thi',
            'canbochamthi' => 'Cán bộ chấm thi',
            'nhomhocphan' => 'Nhóm học phần',
            'filedinhkem' => 'File đính kèm',
            'hocky_id' => 'Học kỳ',
            'namhoc_id' => 'Năm học',
            'monhoc_id' => 'Môn học',
            'loaitailieu_id' => 'Loại tài liệu',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHocky()
    {
        return $this->hasOne(Hocky::className(), ['id' => 'hocky_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoaitailieu()
    {
        return $this->hasOne(Loaitailieu::className(), ['id' => 'loaitailieu_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMonhoc()
    {
        return $this->hasOne(Monhoc::className(), ['id' => 'monhoc_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNamhoc()
    {
        return $this->hasOne(Namhoc::className(), ['id' => 'namhoc_id']);
    }

    public function beforeSave($insert)
    {
        $file = UploadedFile::getInstance($this,'filedinhkem');
        if(is_null($file)){
            if($insert){
                $this->filedinhkem ='nofile.jpg';
            }
            else{
                $old = Ketquadanhgiahocphan::findOne($this->id);
                $this->filedinhkem = $old->filedinhkem;
            }
        }
        else{
            if(!$insert){
                $old = Ketquadanhgiahocphan::findOne($this->id);
                if($old->filedinhkem != 'nofile.jpg'){
                    $path = dirname(dirname(__DIR__)).'/files/'.$old->filedinhkem;
                    unlink($path);
                }
            }
            $fileName = time().myFuncs::sinhDuongDan($file->name);
            $path = dirname(dirname(__DIR__)).'/files/'.$fileName;
            $file->saveAs($path);
            $this->filedinhkem = $fileName;

        }
        if($insert)
            $this->created_at = new Expression("NOW()");
        else
            $this->updated_at = new Expression("NOW()");
        $this->loaitailieu_id = 6;
        $this->ngaythi = myFuncs::dayMonthYeartoYearMonthDay($this->ngaythi);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $file = $this->filedinhkem;
        if($file != 'nofile.jpg');
        $path = dirname(dirname(__DIR__)).'/files'.$file;
        if(is_file($path))
            unlink($path);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
