<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "{{%td_kt_kl}}".
 *
 * @property int $id
 * @property string $name
 * @property int $loaitailieu_id
 *
 * @property Khenthuong[] $khenthuongs
 * @property Kiluat[] $kiluats
 * @property Loaitailieu $loaitailieu
 * @property Thidua[] $thiduas
 */
class TdKtKl extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%td_kt_kl}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required', 'message' => 'Chưa điền {attribute}'],
            [['loaitailieu_id'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['loaitailieu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Loaitailieu::className(), 'targetAttribute' => ['loaitailieu_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên',
            'loaitailieu_id' => 'Loại tài liệu',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKhenthuongs()
    {
        return $this->hasMany(Khenthuong::className(), ['TD_KT_KL_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKiluats()
    {
        return $this->hasMany(Kiluat::className(), ['TD_KT_KL_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoaitailieu()
    {
        return $this->hasOne(Loaitailieu::className(), ['id' => 'loaitailieu_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getThiduas()
    {
        return $this->hasMany(Thidua::className(), ['TD_KT_KL_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->loaitailieu_id = 8;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
